Add removal of keep awake events for cron history
kolyasya/meteor-oplog-keep-awake pull request #1
Opened 2023-11-30 16:56 UTC by eadenink

There is one issue: when interval is more than a minute cron start rounding dates, so for default 120 seconds available 2 latest logs, but for 10 seconds interval only 1

2023-12-01 02:46 UTC, kolyasya requested changes

2023-12-01 02:46 UTC, kolyasya commented on example/packages/oplog-keep-awake/server.js
> +  keepAwakeUpsertIntervalSeconds: 10,
@eadenink you changed a default interval here. We publish the package code from this directory

2023-12-01 02:46 UTC, kolyasya commented on example/packages/oplog-keep-awake/server.js
> +            name: cronOperationName,
@eadenink shouldn't the query be simpler? We can just use regex for `kolyasya:oplog-keep-awake` string

2023-12-01 02:46 UTC, kolyasya commented on example/packages/oplog-keep-awake/server.js
> +            finishedAt: { $lte: new Date(new Date() - packageSettings?.keepAwakeUpsertIntervalSeconds * 1000) }
@eadenink need do add a human readable comment here with the date explanation

2023-12-01 14:10 UTC, eadenink commented on example/packages/oplog-keep-awake/server.js
> +            name: cronOperationName,
Anyway we use this message in cron so I think it's reasonable to use this message also for removal

2023-12-05 08:45 UTC, kolyasya commented on example/packages/oplog-keep-awake/server.js
> +            name: cronOperationName,
@eadenink what if we adjust settings before the next clean-up CRON start? Old log will not be removed from DB

2023-12-05 08:47 UTC, kolyasya commented on example/packages/oplog-keep-awake/server.js
> +            finishedAt: { $lte: new Date(new Date() - packageSettings?.keepAwakeUpsertIntervalSeconds * 1000) } // Delete old package logs from cron history(from current time we subtract cron interva
@eadenink add comment above the line please

2023-12-12 03:58 UTC, merged